// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'db.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DbType`

enum DataType { number, char, time, blob, json, dataSet }

class QueryColumn {
  final String name;
  final DataType dataType;

  const QueryColumn({required this.name, required this.dataType});

  @override
  int get hashCode => name.hashCode ^ dataType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueryColumn &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          dataType == other.dataType;
}

class QueryHeader {
  final List<QueryColumn> columns;
  final BigInt affectedRows;

  const QueryHeader({required this.columns, required this.affectedRows});

  @override
  int get hashCode => columns.hashCode ^ affectedRows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueryHeader &&
          runtimeType == other.runtimeType &&
          columns == other.columns &&
          affectedRows == other.affectedRows;
}

class QueryRow {
  final List<QueryValue> values;

  const QueryRow({required this.values});

  @override
  int get hashCode => values.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueryRow &&
          runtimeType == other.runtimeType &&
          values == other.values;
}

@freezed
sealed class QueryStreamItem with _$QueryStreamItem {
  const QueryStreamItem._();

  const factory QueryStreamItem.header(QueryHeader field0) =
      QueryStreamItem_Header;
  const factory QueryStreamItem.row(QueryRow field0) = QueryStreamItem_Row;
  const factory QueryStreamItem.error(String field0) = QueryStreamItem_Error;
}

@freezed
sealed class QueryValue with _$QueryValue {
  const QueryValue._();

  const factory QueryValue.null_() = QueryValue_NULL;
  const factory QueryValue.bytes(Uint8List field0) = QueryValue_Bytes;
  const factory QueryValue.int(PlatformInt64 field0) = QueryValue_Int;
  const factory QueryValue.uInt(BigInt field0) = QueryValue_UInt;
  const factory QueryValue.float(double field0) = QueryValue_Float;
  const factory QueryValue.double(double field0) = QueryValue_Double;
  const factory QueryValue.dateTime(PlatformInt64 field0) = QueryValue_DateTime;
}
