// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'db.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `sqlite_type_to_data_type`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SqliteConnection>>
abstract class SqliteConnection implements RustOpaqueInterface {
  Future<void> close();

  static Future<SqliteConnection> open({required String dsn}) =>
      RustLib.instance.api.crateApiSqliteSqliteConnectionOpen(dsn: dsn);

  Stream<QueryStreamItem> query({required String query});
}
